import i18n from '../i18n'

const CV_LANGUAGES = ['en', 'ru', 'hy']

/**
 * The CV PDF generated by the backend (GET /api/cv), in the current site language by default.
 * `inline` shows it in the browser instead of downloading it.
 */
export function cvUrl({ lang = i18n.resolvedLanguage, inline = false }: { lang?: string; inline?: boolean } = {}) {
  const language = lang && CV_LANGUAGES.includes(lang) ? lang : 'en'
  return `/api/cv?lang=${language}${inline ? '&download=false' : ''}`
}
